project:
  type: website

website:
  title: "mathslop"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true



