---
title: "Hilbert's Nullstellensatz: Integral Extensions Day 2"
date: 07/03/2026
---

::: {.hidden}
$$
\newcommand{\bA}{\mathbf{A}}
\newcommand{\NN}{\mathbf{N}}
\newcommand{\ZZ}{\mathbf{Z}}
\newcommand{\RR}{\mathbf{R}}
\newcommand{\PP}{\mathbf{P}}
\newcommand{\QQ}{\mathbf{Q}}
\newcommand{\FF}{\mathbf{F}}
\newcommand{\CC}{\mathbf{C}}
\newcommand{\cO}{\mathcal{O}}
\newcommand{\cX}{\mathcal{X}}
\newcommand{\fa}{\mathfrak{a}}
\newcommand{\fb}{\mathfrak{b}}
\newcommand{\fm}{\mathfrak{m}}
\newcommand{\fp}{\mathfrak{p}}
\newcommand{\fP}{\mathfrak{P}}
\newcommand{\fq}{\mathfrak{q}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sB}{\mathscr{B}}
\newcommand{\sF}{\mathscr{F}}
\newcommand{\sG}{\mathscr{G}}
\newcommand{\vp}{\varphi}
\newcommand{\sli}{{s_l}_i}
\newcommand{\smi}{{s_m}_i}
\newcommand{\HomC}{\text{Hom}_{\mathscr{C}}}
\newcommand{\mf}{\mathscr{F}}
\newcommand{\Spec}{\text{Spec}}
\newcommand{\Spa}{\text{Spa}}
\newcommand{\Spf}{\text{Spf}}
\newcommand{\SL}{\text{SL}}
\newcommand{\Frac}{\text{Frac}}
$$
:::

In the last post we defined integral extensions of rings and the notion of a domain integrally closed inside its fraction field. We gave quadratic integer rings as examples of integral extensions of $\ZZ$ and showed that the local ring at the cusp of the cuspidal cubic $Y=Z(y^2-x^3)$ is not integrally closed, giving one illustration of the geometric consequences of (the failure of) integrality. We ended by proving that all unique factorization domains are integrally closed.

In this post we will begin the proof of a proposition characterizing integral elements of a ring extension $S\supset R$.

As with yesterday's post, we more or less follow Chapter 5 of Daniel Coray's [*Notes on Geometry and Arithmetic*](https://link.springer.com/book/10.1007/978-3-030-43781-7), and all rings are commutative with 1.

## Some definitions

For our first result, we will need to define algebras and modules of finite type. We will recall the standard definitions from [Altman-Kleiman](https://www.mi.fu-berlin.de/en/math/groups/arithmetic_geometry/teaching/exercises/Altman_-Kleiman---A-term-of-commutative-algebra-_2017_.pdf).

**Definition 1.** Let $R$ be a ring. An $R$*-algebra* is a ring $R'$ equipped with a ring map $\vp:R\to R'$, called the *structure map*. A homomorphism of $R$-algebras is a ring map that is compatible with the structure maps.

**Definition 2.** We say an $R$-algebra $R'$ with structure map $\vp:R\to R'$ is a *finitely generated* $R$*-algebra* or an $R$*-algebra of finite type* or is *algebra-finite* over $R$ if there exist $x_1,x_2,...,x_n\in R'$ such that $R'=\vp(R)[x_1,x_2,...,x_n].$

**Definition 3.** An $R$-module $M$ is a *finitely generated* $R$*-module* or an $R$-*module of finite type* if $M$ has a finite generating set, that is, there exists a finite set $\{x_1,x_2,...,x_n\}\subset M$ such that for each $m\in M$, there exist $r_1,r_2,...,r_n\in R$ such that $$m=\sum_{k=1}^n r_ix_i.$$

**Example 1.** Consider the polynomial ring $R[x]$ where $R$ is a nonzero ring. This is an $R$-algebra of finite type, but *not* an $R$-module of finite type: for any finite set of elements $f_1,f_2,...,f_n\in R[x]$, any $R$-linear combination of the $f_i$ has degree at most $$\max\{\deg(f_1),\deg(f_2),...,\deg(f_n)\}.$$

This example shows that a finite type $R$-algebra may not be finite type as an $R$-module. With this in mind, we make another definition.

**Definition 4.** An $R$-algebra $R'$ is *module-finite* if it is finitely generated as an $R$-module.

**Example 2.** $\ZZ[i]$ (or any other quadratic integer ring) is both algebra-finite and module-finite over $\ZZ$; algebra-finiteness is clear, and it is also module-finite since each element $\alpha\in \ZZ[i]$ can be written in the form $\alpha=a+bi$ for some $a,b\in \ZZ$.

## A characterization of integral elements

**Proposition 1.** Let $R\subset S$ be two rings and let $\xi\in S$. Then the following are equivalent:

(a) $\xi$ is integral over $R$;
(b) The ring $R[\xi]$ is an $R$-module of finite type;
(c) $R[\xi]$ is contained in a ring $T$, which is an $R$-module of finite type.

*Proof.* $(a\Rightarrow b)$ If $\xi$ is integral over $R$, then there exist $a_0,a_1,...,a_n\in R$ such that $$a_0+a_1\xi+...+a_n\xi^n+\xi^{n+1}=0;$$ in particular, $$\xi^{n+1}=-a_0-a_1\xi-...-a_n\xi^n.$$ For any $f\in R[\xi]$, finitely many applications of this identity to the powers of $\xi$ of degree higher than $n$ will yield an expression for $f$ as a polynomial in $\xi$ of degree at most $n$; thus, $R[\xi]$ is generated as an $R$-module by $\{1,\xi,\xi^2,...,\xi^n\}.$

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Remark.

Here we see one reason why it matters that an integral element satisfy a *monic* polynomial equation: we are guaranteed that *any* scalar multiple of $\xi^{n+1}$ is an $R$-linear combination of lower degree powers of $\xi$. If we only required that $\xi$ satisfy a (not necessarily monic) polynomial equation with coefficients in $R$, we would only be able to say that $$\alpha \xi^{n+1}=-a_0-...-a_n\xi^n$$ for some $\alpha\in R$, and $\alpha$ may not be invertible in $R$.

For example, take $R=\ZZ$, $S=\QQ$, and $\xi=1/2$. $1/2$ is not integral over $\ZZ$, and indeed $\ZZ[1/2]$ is not finitely generated as a $\ZZ$-module, as any finite collection of elements of $\ZZ[1/2]$ has some element with largest denominator, and taking $\ZZ$-linear combinations cannot give us an element of larger denominator. However, $1/2$ is a root of the *non-monic* polynomial $f(x)=2x-1\in \ZZ[x]$.
:::

$(b\Rightarrow c)$ Just take $T=R[\xi].$

$(c\Rightarrow a)$ We will continue with this part tomorrow. Coray gives two proofs; the first is quick, but requires the assumption that $R$ is Noetherian, and the second requires a version of the Cayley-Hamilton theorem for modules. We will give both proofs and aim to make them more self-contained.