---
title: "Hilbert's Nullstellensatz: Integral Extensions Day 3"
date: 07/04/2026
format:
  html:
    include-in-header:
      text: |
        <style>
        .knowl {
          color: var(--bs-link-color);
          text-decoration: underline dotted;
          cursor: pointer;
        }
        .knowl:hover {
          text-decoration: underline;
        }
        </style>
    include-after-body:
      text: |
        <script>
        document.addEventListener("DOMContentLoaded", function () {
          const popoverTriggerList =
            document.querySelectorAll('[data-bs-toggle="popover"]');

          [...popoverTriggerList].map(function (el) {
            return new bootstrap.Popover(el, {
              container: "body"
            });
          });
        });
        </script>
---

::: {.hidden}
$$
\newcommand{\bA}{\mathbf{A}}
\newcommand{\NN}{\mathbf{N}}
\newcommand{\ZZ}{\mathbf{Z}}
\newcommand{\RR}{\mathbf{R}}
\newcommand{\PP}{\mathbf{P}}
\newcommand{\QQ}{\mathbf{Q}}
\newcommand{\FF}{\mathbf{F}}
\newcommand{\CC}{\mathbf{C}}
\newcommand{\cO}{\mathcal{O}}
\newcommand{\cX}{\mathcal{X}}
\newcommand{\fa}{\mathfrak{a}}
\newcommand{\fb}{\mathfrak{b}}
\newcommand{\fm}{\mathfrak{m}}
\newcommand{\fp}{\mathfrak{p}}
\newcommand{\fP}{\mathfrak{P}}
\newcommand{\fq}{\mathfrak{q}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sB}{\mathscr{B}}
\newcommand{\sF}{\mathscr{F}}
\newcommand{\sG}{\mathscr{G}}
\newcommand{\vp}{\varphi}
\newcommand{\sli}{{s_l}_i}
\newcommand{\smi}{{s_m}_i}
\newcommand{\HomC}{\text{Hom}_{\mathscr{C}}}
\newcommand{\mf}{\mathscr{F}}
\newcommand{\Spec}{\text{Spec}}
\newcommand{\Spa}{\text{Spa}}
\newcommand{\Spf}{\text{Spf}}
\newcommand{\SL}{\text{SL}}
\newcommand{\Frac}{\text{Frac}}
$$
:::

As with yesterday's post, we more or less follow Chapter 5 of Daniel Coray's [*Notes on Geometry and Arithmetic*](https://link.springer.com/book/10.1007/978-3-030-43781-7), and all rings are commutative with 1.

## Characterizing integral elements

Recall that yesterday's post ended with the following proposition:

**Proposition 1.** Let $R\subset S$ be two rings and let $\xi\in S$. Then the following are equivalent:

(a) $\xi$ is integral over $R$;
(b) The ring $R[\xi]$ is an $R$-module of finite type;
(c) $R[\xi]$ is contained in a ring $T$, which is an $R$-module of finite type.

[We proved](https://fed-witten.github.io/wed-fitten/posts/july3.html#a-characterization-of-integral-elements) $(a\Rightarrow b)$ and $(b\Rightarrow c)$, so it remains to prove $(c\Rightarrow a)$.


### $(c\Rightarrow a)$

#### First proof

The first proof will be quick, at the cost that we assume that $R$ is `<a tabindex="0" class="knowl" role="button"
data-bs-toggle="popover"
data-bs-trigger="focus"
data-bs-title="Noetherian rings and modules"
data-bs-content="A ring is Noetherian if every ascending chain of ideals stabilizes. Equivalently, a ring is Noetherian if every ideal is finitely generated. Analogously, an R-module is Noetherian if every ascending chain of submodules stabilizes, or equivalently if every submodule is finitely generated.">Noetherian</a>`{=html}. Note that this is not a significant cost for the kind of algebraic geometry and algebraic number theory we will get into.

The reference Coray gives for this proof is the seventh edition of [van der Waerden's book *Algebra*](https://en.wikipedia.org/wiki/Moderne_Algebra) published in 1966. The description of the book on this [Amazon listing](https://www.amazon.com/dp/0804449503?lv=shuf&channelId=500&plpRedirect=mhFallback) is worth looking at.

*Proof.* Suppose $R$ is Noetherian. Then $T$ is a Noetherian $R$-module: $T$ is an $R$-module of finite type by hypothesis, and this holds if and only if there is a surjection $$\bigoplus_{i=1}^n R\twoheadrightarrow T$$ for some $n\in \NN$. Every $R$-submodule of $\oplus_{i=1}^n R$ is finitely generated since every ideal of $R$ is finitely generated, so $\oplus_{i=1}^n R$ is a Noetherian $R$-module. Being a quotient of a Noetherian $R$-module, we conclude that $T$ is itself a Noetherian $R$-module. 

Now, for each nonnegative integer $n$, define $T_n$ to be the $R$-submodule of $T$ generated by $\{1,\xi,\xi^2,...,\xi^n\}$. Since $T$ is Noetherian, the chain $$T_0\subset T_1\subset T_2\subset ...$$ is stationary; that is, there exists an integer $m$ such that $$T_m=T_{m+1}=T_{m+2}=...$$ and in particular $\xi^{m+1}$ is an $R$-linear combination of $1,\xi,\xi^2,...,\xi^m$.

<span style="float: right;">$\square$</span>
\

The second proof drops the assumption that $R$ is Noetherian and uses a version of the Cayley-Hamilton theorem for modules. I do not feel like writing this up, so I direct the reader to Coray's book or to Chapter 10 of [Altman-Kleiman](https://www.mi.fu-berlin.de/en/math/groups/arithmetic_geometry/teaching/exercises/Altman_-Kleiman---A-term-of-commutative-algebra-_2017_.pdf). If I do decide to write it up, I will add it to this post. Tomorrow I will move on to some other general results concerning integral extensions, and the next day we will start on the Weak Nullstellensatz.