---
title: "An Elementary Number Theory Problem"
date: 06/17/26
---

::: {.hidden}
$$
\newcommand{\bA}{\mathbf{A}}
\newcommand{\NN}{\mathbf{N}}
\newcommand{\ZZ}{\mathbf{Z}}
\newcommand{\RR}{\mathbf{R}}
\newcommand{\PP}{\mathbf{P}}
\newcommand{\QQ}{\mathbf{Q}}
\newcommand{\FF}{\mathbf{F}}
\newcommand{\CC}{\mathbf{C}}
\newcommand{\cO}{\mathcal{O}}
\newcommand{\cX}{\mathcal{X}}
\newcommand{\fa}{\mathfrak{a}}
\newcommand{\fm}{\mathfrak{m}}
\newcommand{\fp}{\mathfrak{p}}
\newcommand{\fq}{\mathfrak{q}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sF}{\mathscr{F}}
\newcommand{\sG}{\mathscr{G}}
\newcommand{\vp}{\varphi}
\newcommand{\sli}{{s_l}_i}
\newcommand{\smi}{{s_m}_i}
\newcommand{\HomC}{\text{Hom}_{\mathscr{C}}}
\newcommand{\mf}{\mathscr{F}}
\newcommand{\Spec}{\text{Spec}}
\newcommand{\Spa}{\text{Spa}}
\newcommand{\Spf}{\text{Spf}}
$$
:::

I lied about stopping with competition-style problems. In fact, I am having fun with these, so I will not stop until they stop being fun. I only said I would stop because I felt like I "should" write about something conceptual or high-brow. But you are not my advisor, and this is not my academic website. So I'm gonna keep fucking around.

::: {.callout-note icon=false}
## Problem 70, *The Red Book of Mathematical Problems*, Kenneth S. Williams and Kenneth Hardy

Prove that every integer can be expressed in the form $x^2+y^2-5z^2,$ where $x,y,z$ are integers.
:::

## Solution

### Getting off the ground

Let's make some trivial observations.

**Observation 1.** Taking $y=z=0$, we see that every positive square integer is of this form.

**Observation 2.** Taking $x=2z$ and $y=0$ shows that every negative square integer is of this form.

**Meta-observation 1.** It's really easy to say something about numbers that are squares or certain multiples of squares, but we want to get all integers. To get an arbitrary integer $n$, we should try to define $x,y,z$ in terms of $n$ in such a way that degree 2 terms cancel.

### Getting all odd integers

Fix $z$ and let $x=z+1$, $y=2z$. Then $$x^2+y^2-5z^2=(z^2+2z+1)+4z^2-5z^2=2z+1.$$ Thus, we obtain the odd integer $2z+1$ from the triple $(x,y,z)=(z+1,2z,z).$

### Getting all even integers

It remains to show that any even integer can be written in the desired form. Let's see if we can take the equation $$(z+1)^2+(2z)^2-5z^2=2z+1$$ and make some change to the left-hand side that results in adding an odd integer to the right-hand side. Since $$(2z+1)^2=(2z)^2+4z+1,$$ we see that to substitute $2z+1$ for $2z$ we have to add $4z+1$ to the right-hand side: $$(z+1)^2+(2z+1)^2-5z^2=(2z+1)+(4z+1)=6z+2.$$ We succeeded in adding $1$, but paid the cost of also adding $4z$. Fortunately, $$(z-1)^2=(z+1)^2-4z,$$ so substituting $z-1$ for $z+1$ results in adding $-4z$ to the right-hand side: $$(z-1)^2+(2z+1)^2-5z^2=(6z+2)+(-4z)=2z+2.$$ Thus, we obtain the even integer $2z+2=2(z+1)$ from the triple $(x,y,z)=(z-1,2z+1,z).$

## Job's Not Finished

https://youtu.be/fY7l2pcxdHM?si=TxRsTObaMGatrn1g

We solved the problem, but our job is not finished. Do we understand *why* all integers can be represented in the form $x^2+y^2-5z^2$? Who cares? What happens if we change $5$ to some other integer?

### Variation 1

Suppose we replace $5$ with some other integer $n$. Can we still represent an arbitrary integer in the form $x^2+y^2-nz^2$?

Clearly not if $n=0$: Not all integers are sums of two squares. For example, $3$ is not a sum of two squares. In fact, any member of the residue class $3$ mod $4$ eludes being written as a sum of two squares, as $0$ and $1$ are the only squares mod $4$.

If $n<0$, then $x^2+y^2-nz^2\geq 0,$ so clearly we cannot get every integer this way. Maybe we can get every nonnegative integer? This seems like a good question. Let us call this

#### Case 1

Let $n\in \ZZ^+$. Can every nonnegative integer be written in the form $x^2+y^2+nz^2$ for some integers $x,y,z$?

If we let $n=1$, we see after a little bit of checking that we can't. We get $3=1^2+1^2+1^2$ and $6=2^2+1^2+1^2$, but we cannot write $7$ as a sum of three squares. In fact, since $\{0,1,4\}$ are all the squares mod $8$, the entire residue class $7$ mod $8$ eludes being written as a sum of three squares. 

::: {.callout-note collapse="true" icon=false appearance="simple"}
## What about sums of four squares?

Above we showed that sums of two squares miss the residue class $3$ mod $4$, and that sums of three squares miss the residue class $7$ mod $8$. Do sums of four squares miss the residue class $15$ mod $16$?

The answer is no. Let's examine the set of squares mod $16$: 
$$
\begin{aligned}
1^2 &= 1,\text{ }2^2=4,\text{ }3^2=9,\text{ }4^2=0,\text{ }5^2=9,\text{ }6^2=4,\text{ }7^2=1,\text{ }8^2=0,\text{ }9^2=1,\\
\text{ }10^2 &= 4,\text{ }11^2=9,\text{ }12^2=0,\text{ }13^2=9,\text{ }14^2=4,\text{ }15^2=1.
\end{aligned}
$$ *Exercise: Find a quicker way to determine all the squares mod $16$.*

We see that $\{0,1,4,9\}$ is the set of all squares mod $16$. We can get every residue class mod $16$ from sums of four of these: $2=0+0+1+1$ and $3=0+1+1+1$; $5=4+1+0+0$, $6=4+1+1+0$, $7=4+1+1+1$, $8=4+4+0+0$; $10=9+1+0+0$, $11=9+1+1+0$, $12=9+1+1+1$, $13=9+4+0+0$, $14=9+4+1+0$, $15=9+4+1+1$. Thus, sums of four squares *do* hit every residue class mod $16$.

It turns out to be true that every nonnegative integer can be written as a sum of four square integers, a fact known as Lagrange's four-square theorem (https://en.wikipedia.org/wiki/Lagrange%27s_four-square_theorem). This will likely be the topic of a future post.

:::

I'm going to stop doing math here, and maybe I will continue this tomorrow. Let us finish this post by collecting the other obvious case and the questions we want to think about.

### Case 2

Let $n\in \ZZ^+$. Can every integer be written in the form $x^2+y^2-nz^2$ for some integers $x,y,z$?

### Questions

Do we understand why all integers can be represented in the form $x^2+y^2-5z^2$? Who cares?

*Remark.* Just to give an example of what "understanding" might look like. It is true that a product of two sums of squares is itself a sum of two squares, and a product of a sum of four squares is itself a sum of four squares. It is not obvious why this is if we just think in terms of arithmetic. But these are both pretty trivial when we see a sum of squares as the modulus of a complex number and a sum of four squares as the modulus of a quaternion. These facts are then just an expression of the fact that the modulus in each setting is multiplicative, i.e. $$|\alpha \beta|=|\alpha|\cdot|\beta|$$ for all $\alpha,\beta$ both complex numbers or both quaternions. See e.g. *Naive Lie Theory* by John Stillwell and [this note](https://kconrad.math.uconn.edu/blurbs/linmultialg/pfister.pdf) from Keith Conrad.