---
title: "Problem B2, 2022 Putnam Mathematical Competition"
date: 06/14/26
---

::: {.hidden}
$$
\newcommand{\bA}{\mathbf{A}}
\newcommand{\NN}{\mathbf{N}}
\newcommand{\ZZ}{\mathbf{Z}}
\newcommand{\RR}{\mathbf{R}}
\newcommand{\PP}{\mathbf{P}}
\newcommand{\QQ}{\mathbf{Q}}
\newcommand{\FF}{\mathbf{F}}
\newcommand{\CC}{\mathbf{C}}
\newcommand{\cO}{\mathcal{O}}
\newcommand{\cX}{\mathcal{X}}
\newcommand{\fa}{\mathfrak{a}}
\newcommand{\fm}{\mathfrak{m}}
\newcommand{\fp}{\mathfrak{p}}
\newcommand{\fq}{\mathfrak{q}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sF}{\mathscr{F}}
\newcommand{\sG}{\mathscr{G}}
\newcommand{\vp}{\varphi}
\newcommand{\sli}{{s_l}_i}
\newcommand{\smi}{{s_m}_i}
\newcommand{\HomC}{\text{Hom}_{\mathscr{C}}}
\newcommand{\mf}{\mathscr{F}}
\newcommand{\Spec}{\text{Spec}}
\newcommand{\Spa}{\text{Spa}}
\newcommand{\Spf}{\text{Spf}}
$$
:::

## Introduction

*Note.* I do plan to write about stuff more interesting than competition math eventually.

I might as well talk about the Putnam problem I did solve since it involves writing about myself and math I already know. I remember much more about my thought process here than with problem B3, so I will try to reproduce that thread of thought rather than simply writing down a proof.


## The Problem

::: {.callout-note icon=false}
## Problem B2, 2022 Putnam Mathematical Competition

Let $\times$ represent the cross product in $\RR^3$. For what positive integers $n$ does there exist a set $S\subset \RR^3$ with exactly $n$ elements such that $$S=\{v\times w:v,w\in S\}?$$
:::

### First observations

Since this problem involves cross products, we might as well write down some of the important properties of the cross product that we might want to use.

::: {.callout-note icon=false}
## Properties of the cross product.

1. For all $v,w\in \RR^3$, $v\times w$ is orthogonal to both $v$ and $w$.
2. $v\times w=-w\times v$ for all $v,w\in \RR^3$.
3. $\|v\times w\|=\|v\|\cdot\|w\|\sin\theta$ for all $v,w\in \RR^3$ where $\theta$ is the angle between $v$ and $w$.
:::

Ok, this is good stuff to have ready, but it doesn't point towards any particular strategy. As a general rule, if you are asked a question that depends on a natural number $n$ and you have no other ideas about what to do, you should start by checking what happens for some small values of $n.$ Let us start by doing this.

### Small $n$ casework

Taking $S=\{0\}$ (where $0$ denotes the zero vector) shows that $n=1$ works, as $0\times 0=0$. 

The next case to consider is when $S$ contains some nonzero vector $v$. It follows that $0\in S$ since $v\times v=0$ (by Property 3 above). Is it possible that $S=\{0,v\}$? Recall that $S$ is equal to the set of all cross products of pairs of elements in $S$. Since $$0\times 0=0\times v=v\times 0=v\times v=0,$$ we see that $v$ is not the cross product of any pair of elements in $\{0,v\}$. Since $v$ is nonzero, it must be the cross product of two nonzero elements of $S$ both orthogonal to $v$, so $v=u\times w$ for some nonzero $u,w\in S$.

Starting from a nonzero vector $v\in S$, we used the definition of $S$ and Property 1 to come up with two new vectors in $S$. We might as well continue down the list of properties and if we can continue generating new elements of $S$.

We know that $u,w,$ and $v=u\times w$ are all in $S$. It follows from the definition of $S$ that $w\times u$ is also in $S$, and Property 2 implies that $$w\times u=-u\times w=-v\in S.$$ Similarly, $u$ and $w$ are both cross products of elements of $S$ by the definition of $S$, so $-u,-w\in S$ as well. Thus, $$\{0,u,v,w,-u,-v,-w\}\subset S.$$

**Insight.** If we take $u={\bf i}$, $w={\bf j}$, $v={\bf k}$ where ${\bf i}, {\bf j}, {\bf k}$ are the standard basis vectors for $\RR^3$, we in fact have (exercise for the reader!) $$S=\{0,\pm {\bf i}, \pm {\bf j}, \pm {\bf k}\}.$$ At this point we have shown that $n=1$ and $n=7$ work, and if $S$ contains a nonzero vector then $n=|S|\geq 7$.

### Wielding Property 3

The results we obtained above seem like a natural stopping point where we should change direction; we cannot do casework forever, after all. We can make two important observations about the work we've done so far:

**Observation 1.** In all the cases we've discovered so far that work ($n=1$ and $n=7$), all the vectors in $S$ have norm equal to 0 or 1.

**Observation 2.** We've yet to (meaningfully) use Property 3 of the cross product.

Let us return to the case where $S$ contains some nonzero vector $v$, where we found that $v=u\times w$ for some $u,w\in S$ and $$\{0,u,v,w,-u,-v,-w\}\subset S.$$ What happens if $\|v\|\neq 1$? By the definition of $S$, we know that $v\times w\in S$; similarly, $v^n\times w\in S$ for all $n\in \ZZ^+$, where we write $v^n$ for the $n$-fold product $v\times v \times ...\times v$,  and $v^{m}\times w$ is orthogonal to $v^{n}\times w$ for all $1\leq m<n\in \ZZ^+$ by Property 1. Repeated application of Property 2 (writing this up properly would use induction, which I did on the exam but will not do here) shows that $$\|v^n\times w\|=\|v\|^n\cdot \|w\|$$ for all $n\in \ZZ^+$. If $\|v\|\neq 1$, then $$\{\|v\|^n\cdot\|w\|:n\in \ZZ^+\}$$ is an infinite set since $\|v\|^m\neq \|v\|^n$ whenever $m\neq n$. Thus, $\|v\|\neq 1$ implies that $S$ contains the infinite set $$\{v^n\times w:n\in \ZZ^+\},$$ so the only way $S$ can be finite is if *all* the nonzero vectors in $S$ have norm equal to 1.

The solution is completed with the

::: {.callout-note icon=false}
## Exercise.

Show that if $S$ is finite, all nonzero vectors in $S$ have norm 1, and there exists a nonzero vector $v\in S$, then $n=|S|=7$.
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Hint 1.

Start as follows: As in the "Small $n$ casework" section, we know that $S$ contains at least 7 elements $0,\pm u,\pm v,\pm w$ where $u,w$ are such that $u\times w=v$.
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Hint 2.

What happens if $u,v,w$ are all orthogonal?
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Hint 3.

$$1=\|v\|=\|u\times w\|=\|u\|\|w\|\sin\theta=\sin\theta$$ where $\theta$ is the angle between $u$ and $w$ by Property 3 and the fact that we assumed $u,v,w$ have norm 1.
:::