---
title: "The Prime Spectrum of a Ring"
date: 06/19/26
---

::: {.hidden}
$$
\newcommand{\bA}{\mathbf{A}}
\newcommand{\NN}{\mathbf{N}}
\newcommand{\ZZ}{\mathbf{Z}}
\newcommand{\RR}{\mathbf{R}}
\newcommand{\PP}{\mathbf{P}}
\newcommand{\QQ}{\mathbf{Q}}
\newcommand{\FF}{\mathbf{F}}
\newcommand{\CC}{\mathbf{C}}
\newcommand{\cO}{\mathcal{O}}
\newcommand{\cX}{\mathcal{X}}
\newcommand{\fa}{\mathfrak{a}}
\newcommand{\fb}{\mathfrak{b}}
\newcommand{\fm}{\mathfrak{m}}
\newcommand{\fp}{\mathfrak{p}}
\newcommand{\fP}{\mathfrak{P}}
\newcommand{\fq}{\mathfrak{q}}
\newcommand{\id}{\mathrm{id}}
\newcommand{\sB}{\mathscr{B}}
\newcommand{\sF}{\mathscr{F}}
\newcommand{\sG}{\mathscr{G}}
\newcommand{\vp}{\varphi}
\newcommand{\sli}{{s_l}_i}
\newcommand{\smi}{{s_m}_i}
\newcommand{\HomC}{\text{Hom}_{\mathscr{C}}}
\newcommand{\mf}{\mathscr{F}}
\newcommand{\Spec}{\text{Spec}}
\newcommand{\Spa}{\text{Spa}}
\newcommand{\Spf}{\text{Spf}}
\newcommand{\SL}{\text{SL}}
$$
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Edit Log

6/19: Added "Definition," "Some intuition/motivation," "Lemma 10.17.2," and "Some Problems" sections. Gave the definition of spectrum, gave some (incomplete) explanation of the topological space we will get and stated that principal opens correspond to localizations at elements. Gave a "peek towards affine schemes" that (incompletely) highlights the role of the principal opens for defining the structure sheaf of an affine scheme. Gave the spectra of $k[x]$ and $\ZZ$ as examples; would like to add explanations of how the principal opens here correspond to spectra of localizations. Proved parts (1)-(3) of Lemma 10.17.2. Solved Exercise 2.23 from Altman-Kleiman; started Exercise 13.18.
:::

This next sequence of posts will just be me (re-)working through some basic commutative algebra. I will probably spend more than one day each post. To hold myself accountable, I will put an "edit log" in the beginning detailing what progress I made each day. Thus, this page will be something of a "construction zone" until I move on to the next separate post. In particular, I will try to grind through a bunch of technical details first before making it a coherent expository post.

The main reference/starting point is https://stacks.math.columbia.edu/tag/00DY. This is not a good place for a beginner to learn commutative algebra; for that I would recommend [Altman-Kleiman](https://www.mi.fu-berlin.de/en/math/groups/arithmetic_geometry/teaching/exercises/Altman_-Kleiman---A-term-of-commutative-algebra-_2017_.pdf). The goal will be to add some examples and non-technical comments where they make sense (to me) and to prove (some of) the stated results ourselves. I will also do some problems from Altman-Kleiman.

All rings are commutative with $1$, and ring maps send $1$ to $1$.

## Definition

Here we copy Definition 10.17.1 from the Stacks Project.

1. The (prime) spectrum of a ring $R$ is the set of prime ideals of $R$, which we denote by $\Spec(R).$
2. Given a subset $T\subset R$, define $$V(T)=\{\fp\in \Spec(R):\fp\supset T\}.$$
3. Given $f\in R$, let $$D(f)=\{\fp\in \Spec(R):f\notin \fp\}.$$

### Some intuition/motivation

Perhaps we should make some comments as to where we are going with this. We will show that the set $\Spec(R)$ can be given the structure of a topological space when we define the closed sets to be exactly the $V(T)$ above; the resulting topology is called the *Zariski topology*. We will see that the sets $D(f)$ are open and form a basis for the Zariski topology; these will be called the *basic* or *principal* open sets.

Further, we will see that each $D(f)$ is homeomorphic to $\Spec(R_f)$, where $R_f$ denotes the localization of $R$ at the multiplicative set $\{1,f,f^2,f^3,...\}.$ One can think of this ring as $R[f^{-1}]$; in fact $R_f$ and $R[f^{-1}]$ are canonically isomorphic. We will show this when we discuss localization.

::: {.callout-note collapse="true" icon=false appearance="simple"}
## A peek towards affine schemes.

The way Grothendieck defines the structure sheaf on $\Spec(R)$ in EGA 1 is (very) roughly as follows. 

Given a topological space $X$, he introduces the notion of a presheaf $\sF$ defined on a basis for the topology $X$, then shows how to get a presheaf $\sF'$ on $X$ agreeing with $\sF$ on our basis.

Then, one can simply define the structure sheaf as the sheafification of the presheaf $$D(f)\mapsto R_f$$ defined on the basis of principal opens. Of course, one has to show that this assignment actually is a presheaf, and that this gives $\Spec(R)$ the structure of a locally ringed space. We will talk about this stuff eventually.
:::

### Observations and Examples

**Observation 1.** If $T\subset R$, let $(T)$ denote the ideal generated by the elements of $T$. If $\fp\in \Spec(R)$ contains $T$ then it also contains $(T)$ since the ideal generated by any subset of $\fp$ must be contained in the ideal generated by $\fp$, which is just $\fp$. Clearly $(T)\subset \fp$ implies $T\subset \fp$ as well. Thus, we could have equivalently defined the closed sets to be the sets $V(I)$ where $I$ is an ideal of $R$.

For a moment, take for granted that the definition of the Zariski topology above indeed defines a topology on $\Spec(R)$; we will show this later.

**Example 1.** Let $k$ be an algebraically closed field and let $R=k[x]$. Then $$\Spec(R)=\{(0)\}\cup\{(x-a):a\in k\}.$$ Since $(0)\subset \fp$ for all $\fp\in \Spec(R)$, we see that $$V((0))=R;$$ this means that in the Zariski topology, the closure of $(0)$ is equal to the whole space $\Spec(R)$. We say that $(0)$ is the *generic point* of $\Spec(R)$. The reason we are justified in called $(0)$ *the* generic point is because for all $a\in k$, the prime ideal $(x-a)$ is maximal, so $$V((x-a))=\{(x-a)\}.$$ If we take an arbitrary $f\in k[x]$, then $f$ factors uniquely into a procuct of a constant and some monic linear polynomials $$f=\alpha\prod_{i=1}^n (x-a_i),\text{ }\alpha,a_i\in k$$ since $k$ is an algebraically closed field and $k[x]$ is both a PID and a UFD. Thus, $$D(f)=\{(x-\lambda):\lambda\in k\setminus\{a_1,a_2,...,a_n\}\}.$$

**Example 2.** $\Spec(\ZZ)=\{(0)\}\cup \{(p):p\text{ prime}\}.$ Again, $(0)$ is the unique generic point, and all the nonzero prime ideals are maximal. Given an integer $n$, $$D(n)=\{p\in \ZZ:p\text{ prime and} \gcd(p,n)=1\}.$$

These examples are not typical, since both are integral domains of Krull dimension 1. We'll end up discussing more examples later on.

## Lemma 10.17.2.

This lemma has 17 parts. We'll aim to prove them them one by one. If I successfully come up with my own proof, that is what I'll include. If I cannot do that, I'll include my thought process, then get a next idea from their proof, try to explain it to myself, and repeat.

::: {.callout-note collapse="true" icon=false appearance="simple"}
## (1) The spectrum of a ring $R$ is empty if and only if $R$ is the zero ring.

*Proof.* If $R$ is the zero ring, then the unique ideal $(0)$ of $R$ is equal to $R$, hence is not a prime ideal. Thus, $\Spec(R)$ is empty.

Conversely, suppose that $\Spec(R)$ is empty. Then $R$ must be the zero ring, since a standard application of Zorn's lemma shows that every nonzero ring has a maximal (hence prime) ideal. See (2).
<span style="float: right;">$\square$</span>
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## (2) Every nonzero ring has a maximal ideal.

This is a standard argument I have seen before in many places, e.g. Atiyah-MacDonald or Altman-Kleiman.

The idea is pretty simple. Zorn's lemma says that if we have a partially ordered set $S$, and every totally ordered subset (chain) of $S$ has an upper bound, then $S$ has at least one maximal element. Ideals form a partially ordered set under inclusion, and for any chain of ideals, it's pretty easy to show that the union of all the ideals in the chain is itself an ideal. We need to apply this reasoning to proper ideals in order to show that a maximal ideal exists (since a maximal ideal is proper by definition).

*Proof.* The proper ideals of $R$ form a partially ordered set under inclusion. Since $R$ is nonzero, this partially ordered set is nonempty, as it contains the proper ideal $(0)$. Let $\{I_\lambda\}_{\lambda\in \Lambda}$ be a chain of proper ideals of $R$, and let $$I=\bigcup_{\lambda\in \Lambda}I_\lambda.$$ Since the $I_\lambda$ form a totally ordered set, if $x,y\in I$, then $x\in I_{\lambda_1}$ and $y\in I_{\lambda_2}$ for some $\lambda_1,\lambda_2\in \Lambda$; without loss of generality, $I_{\lambda_1}\supset I_{\lambda_2}.$ Hence $x+y\in I_{\lambda_1}\subset I$ and $rx\in I_{\lambda_1}$ for all $r\in R$ since $I_{\lambda_1}$ is an ideal of $R$. Since each $I_\lambda$ is a proper ideal, $1\notin I_\lambda$ for all $\lambda\in \Lambda$, and therefore $1\notin I$. Thus, $I$ is a proper ideal of $R$ and is an upper bound for the chain $\{I_\lambda\}_{\lambda\in \Lambda},$ so Zorn's lemma implies that the set of all proper ideals of $R$ contains a maximal element, hence $R$ contains a maximal ideal.
<span style="float: right;">$\square$</span>

A completely analogous argument shows that any proper ideal of $R$ is contained in a maximal ideal.
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## (3) Every nonzero ring has a minimal prime ideal.

Given an ideal $I$ of a ring $R$, a prime ideal $\fp$ is a minimal prime ideal over $I$ if it is minimal (with respect to inclusion) among all prime ideals containing $I$. A prime ideal $\fp$ is called a minimal prime ideal of $R$ if $\fp$ is a minimal prime ideal over the zero ideal $(0)$.

*Caution*. The zero ideal $(0)$ will fail to be prime when $R$ has zero divisors. For example, $(0)$ is not prime in the ring $$R=\CC[x]/(x^2)$$ since $x\cdot x\in (0)$ but $x\notin (0)$. So this result is nontrivial.

*Proof.* Define a partial order on the set of prime ideals of $R$ by *reverse* inclusion, i.e. $\fp_1\leq \fp_2$ if $\fp_1\supset \fp_2$. Since we assumed $R$ is nonzero, (2) implies that $R$ contains a maximal ideal; since maximal ideals are prime, the set of prime ideals of $R$ is nonempty. In particular, a maximal ideal serves as an upper bound for the empty chain. 

Now let $\{\fp_\lambda\}_{\lambda\in \Lambda}$ be a nonempty chain of prime ideals of $R$ and let $$\fP=\bigcap_{\lambda\in \Lambda}\fp_\lambda.$$ An arbitrary intersection of ideals is an ideal, so $\fP$ is an ideal of $R$. 

We now prove that $\fP$ is prime by contrapositive. First, note that $\fP$ is proper since $\fP\subset \fp_\lambda$ for all $\lambda$ and each $\fp_{\lambda}$ is a prime ideal, hence a proper ideal. If $x\notin \fP$ and $y\notin \fP$, then there exists some $\fp_{\lambda_1}$ not containing $x$ and some $\fp_{\lambda_2}$ not containing $y$. Since $\{\fp_\lambda\}_{\lambda\in \Lambda}$ is totally ordered, there exists a $\fp_{\lambda_3}$ such that $\fp_{\lambda_3}\subset \fp_{\lambda_1}$ and $\fp_{\lambda_3}\subset \fp_{\lambda_2}$ and therefore $x\notin \fp_{\lambda_3}$ and $y\notin \fp_{\lambda_3}$. Since $\fp_{\lambda_3}$ is prime, $xy\in \fp_{\lambda_3}$ implies $x\in \fp_{\lambda_3}$ or $y\in \fp_{\lambda_3}$, so we conclude that $xy\notin \fp_{\lambda_3}$ and therefore $xy\notin \fP$.

Thus, $\fP$ is an upper bound for the chain $\{\fp_{\lambda}\}_{\lambda\in \Lambda}$, and Zorn's lemma implies that $\Spec(R)$ has an element maximal with respect to the partial order $\leq$, which is to say that $\Spec(R)$ has an element minimal with respect to the partial order $\subset$.
<span style="float: right;">$\square$</span>
:::

## Some Problems

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Altman-Kleiman Exercise (2.23)

Let $\fa$ and $\fb$ be ideals, and $\fp$ a prime ideal. Prove that these conditions are equivalent: (1) $\fa\subset \fp$ or $\fb\subset \fp$, (2) $\fa\cap\fb\subset \fp$, (3) $\fa\fb\subset \fp.$

*Proof.* $(1)\Rightarrow (2)$: WLOG, $\fa\subset \fp$. Then $\fa\cap\fb\subset \fa\subset \fp$. $(2)\Rightarrow (3)$: Recall that $\fa\fb$ is defined to be the ideal generated by all products $ab$ with $a\in \fa,b\in \fb$. Since $\fa,\fb$ are ideals, $ab\in \fa\cap \fb$ for all $a\in\fa,b\in\fb$, so the ideal generated by all such products is contained in $\fa\cap\fb$. $(3)\Rightarrow (1)$: (3) We prove the contrapositive. Suppose neither $\fa$ nor $\fb$ is contained in $\fp$. Then there exists some $a\in \fa$, $a\notin \fp$ and $b\in \fb$, $b\notin \fp$. Then $ab\notin \fp$ since $ab\in \fp$ implies $a\in \fp$ or $b\in \fp$. Thus, $\fa\fb$ is not contained in $\fp$.
<span style="float: right;">$\square$</span>
:::

::: {.callout-note collapse="true" icon=false appearance="simple"}
## Altman-Kleiman Exercise (13.18)

Let $R$ be a ring and set $X:=\Spec(R)$. Let $X_1,X_2\subset X$ be closed subsets. Show that the following four statements are equivalent:

(1) $X_1\sqcup X_2=X$, i.e. $X_1\cup X_2=X$ and $X_1\cap X_2=\emptyset$.
(2) There are complementary idempotents $e_1,e_2\in R$ with $V((e_i))=X_i.$
(3) There are comaximal ideals $\fa_1,\fa_2\subset R$ with $\fa_1\fa_2=0$ and $V(\fa_i)=X_i$.
(4) There are ideals $\fa_1,\fa_2\subset R$ with $\fa_1\oplus \fa_2=R$ and $V(\fa_i)=X_i$.

Finally, given any $e_i$ and $\fa_i$ satisfying (2) and either (3) or (4), necessarily $e_i\in \fa_i$.

*Proof.* First we recall the necessary definitions. $e_1,e_2$ are *complementary idempotents* if $e_1^2=1=e_2^2$, $e_1e_2=0$, and $e_1+e_2=1$. Two ideals $\fa_1,\fa_2$ of $R$ are *comaximal* if $\fa_1+\fa_2=(1)=R$.

$(1)\Rightarrow (3)$: Since $X_1,X_2$ are closed subsets of $\Spec(R)$, the definition of the Zariski topology implies that $$X_1=V(\fa_1),\text{ }X_2=V(\fa_2)$$ for some ideals $\fa_1,\fa_2\subset R$. Our assumptions together with Exercise 2.23 imply that $$X_1\cup  X_2=V(\fa_1)\cup V(\fa_2)=V(\fa_1\cap \fa_2)=V(\fa_1\fa_2)=X.$$ *To be continued...*
<span style="float: right;">$\square$</span>
:::